@startuml

class ValidationController
ValidationController ---> Application.Domain.ValidationInteractor
ValidationController ---> Application.Metrics.ITrace
class ValidationInteractor
ValidationInteractor ---> "2" Application.Domain.IGetMaximumQuery
class ITrace
ITrace ---> Application.Metrics.Trace

interface IGetMaximumQuery {
  GetMaximumQuery
}
class GetMaximumQuery
  +Execute()
}
GetMaximumQuery ---> IGetMaximumQuery
interface ITrace {
  TraceBuilder
}
class TraceBuilder
  +Add()
}
TraceBuilder ---> ITrace

@enduml

