@startuml

class ValidationController {
  +Get()
}
ValidationController ---> Application.Domain.ValidationInteractor
ValidationController ---> Application.Metrics.ITrace
class ValidationInteractor {
  +Execute()
}
ValidationInteractor ---> "2" Application.Domain.IGetMaximumQuery
class ITrace {
  +Add()
}
ITrace ---> Application.Metrics.Trace

interface IGetMaximumQuery {
  GetMaximumQuery
}
class GetMaximumQuery {
  +Execute()
}
GetMaximumQuery ---> IGetMaximumQuery
interface ITrace {
  TraceBuilder
}
class TraceBuilder {
  +Add()
}
TraceBuilder ---> ITrace

@enduml

